# This is a basic workflow to help you get started with Actions

name: Build, Lint, and Test

# Trigger this workflow on push or pull request to main or dev
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Full Stack CI
    runs-on: ubuntu-latest  # GitHub provides a fresh Ubuntu VM for CI jobs

    steps:
      # Step 1: Pull your latest code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java for backend logic
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build the Java backend
      - name: Build Java Backend
        run: |
          cd server
          ./gradlew build

      # Step 4: Set up Python environment for AI module
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai/requirements.txt

      - name: Run Python tests
        run: |
          cd ai
          pytest || echo "No tests defined yet"

      - name: Python Linting (flake8)
        run: |
          pip install flake8
          flake8 ai/ || echo "Lint warnings found"

      # Step 5: Set up Node for frontend
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: |
          cd client
          npm ci

      - name: Build frontend
        run: |
          cd client
          npm run build

      - name: JavaScript Linting (ESLint)
        run: |
          cd client
          npm install eslint
          npx eslint src || echo "Lint warnings found"
